ALTER TABLE relation ADD kind SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE relation ADD id BIGSERIAL NOT NULL;

ALTER TABLE relation DROP CONSTRAINT relation_pk;
ALTER TABLE relation ADD CONSTRAINT relation_pk PRIMARY KEY (id);

ALTER TABLE relation ALTER COLUMN group_to_id DROP NOT NULL;
